version: 2

models:
  - name: dim_customers
    description: 'final dimension for customers'

    columns:
      - name: customer_id
        description: This is a unique identifier for the event
        tests:
            - unique
            - not_null
      - name: new_field2
        description: added for tesing purposes
        